version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.5.0
  aws-ecs: circleci/aws-ecs@1.0.0
workflows:
  #build-and-push-image:
  build-and-deploy:
    jobs:
      #- aws-ecr/build_and_push_image:
      - aws-ecr/build-and-push-image:
          #account-url: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com"
          #account-url: AWS_ECR_ACCOUNT_URL
          repo: "${AWS_RESOURCE_NAME_PREFIX}"
          create-repo: true
          # region: ${AWS_DEFAULT_REGION}¥
          region: AWS_DEFAULT_REGION

      - aws-ecs/deploy-service-update:
          requires:
            #- aws-ecr/build_and_push_image
             - aws-ecr/build-and-push-image
          aws-region: ${AWS_DEFAULT_REGION}
          family: "${TASK_DEFINITION}"
          cluster-name: "${CLUSTER_NAME}"
          container-image-name-updates: "container=django,image-and-tag=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/django-sample:latest"